version: '3.4'

services:
  caboodle-frontend:
    image: caboodlefrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    container_name: caboodle-frontend
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/site/app
      - /site/app/node_modules
